In [3]:
!pip install pandas

In [3]:
import pandas as pd
import numpy as np

In [4]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [5]:
np.arange(0,20).reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [6]:
data = pd.DataFrame(np.arange(0,20).reshape(5,4),index=['Row1','Row2','row3','row4','row5'],columns=['column1','column2','column3','column4'])

In [7]:
data

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [8]:
#csv means data is presented in comma seperated format
data.to_csv('test1.csv')

In [9]:
data.loc['Row1']

column1    0
column2    1
column3    2
column4    3
Name: Row1, dtype: int32

In [10]:
type(data.loc['Row1'])

pandas.core.series.Series

In [11]:
# retrieve all rows and columns
data.iloc[:,:]

column1  column2  column3  column4
Row1        0        1        2        3
Row2        4        5        6        7
row3        8        9       10       11
row4       12       13       14       15
row5       16       17       18       19

In [12]:
# remove column 1 
data.iloc[:,1:]

column2  column3  column4
Row1        1        2        3
Row2        5        6        7
row3        9       10       11
row4       13       14       15
row5       17       18       19

In [13]:
# if you need 3 rows and 2 columns

data.iloc[0:3,0:2]

column1  column2
Row1        0        1
Row2        4        5
row3        8        9

In [14]:
data1 = data.iloc[:,:].values

In [15]:
data1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [16]:
type(data1)

numpy.ndarray

In [17]:
data.isnull().sum()

column1    0
column2    0
column3    0
column4    0
dtype: int64

In [18]:
data['column1'].value_counts()

0     1
4     1
8     1
12    1
16    1
Name: column1, dtype: int64

In [19]:
data1[0][0]

0

In [20]:
data1[1][0]

4

In [21]:
data1[2][3]

11

In [22]:
num = len(data1)
for i in range(num):
    print(data1[i][0])

0
4
8
12
16


In [23]:
import pandas as pd
def New_interpolation(x,y,xi):
    n = len(x)   # number of datapoints 
    
# initialize divided difference, f(x) values at different degrees, and error value

    fdd = [[None for x in range(n)] for x in range(n)]
    yint =[None for x in range(n)]
    err = [None for x in range(n)]
    
# Finding divided difference
    
    for i in range(n):
        fdd[i][0] = y[i]
    for j in range(1,n):
        for i in range(n-j):
            fdd[i][j] = (fdd[i+1][j-1] - fdd[i][j-1])/(x[i+j]-x[i])
# Printing fdd here

    fdd_table = pd.DataFrame(fdd)
    print(fdd_table)
    
# interpolating xi
    xterm = 1
    yint[0] = fdd[0][0]
    for order in range(1,n):
        xterm = xterm * (xi - x[order-1])
        yint2 = yint[order-1] + fdd[0][order]*xterm
        err[order-1] = yint2 - yint[order-1]
        yint[order] = yint2
        
# returning a map for pandas dataframe
    return map(lambda y,e : [y,e], yint, err)

In [24]:
x = [1, 4, 6, 5, 3, 1.5, 2.5, 3.5]
y = [0,1.3862944, 1.7917595, 1.6094379, 1.0986123, 0.4054641, 0.9162907, 1.2527630]
a = New_interpolation(x,y,2)
df = pd.DataFrame(a,columns=['f(x)','error'])

          0         1         2         3         4         5         6  \
0  0.000000  0.462098 -0.051873  0.007866 -0.001956  0.000908 -0.000301   
1  1.386294  0.202733 -0.020411  0.003953 -0.001502  0.000456 -0.000110   
2  1.791759  0.182322 -0.024364  0.007709 -0.002186  0.000511       NaN   
3  1.609438  0.255413 -0.059053  0.015361 -0.003464       NaN       NaN   
4  1.098612  0.462099 -0.097456  0.020557       NaN       NaN       NaN   
5  0.405464  0.510827 -0.087177       NaN       NaN       NaN       NaN   
6  0.916291  0.336472       NaN       NaN       NaN       NaN       NaN   
7  1.252763       NaN       NaN       NaN       NaN       NaN       NaN   

          7  
0  0.000076  
1       NaN  
2       NaN  
3       NaN  
4       NaN  
5       NaN  
6       NaN  
7       NaN  


In [25]:
df

f(x)     error
0  0.000000  0.462098
1  0.462098  0.103746
2  0.565844  0.062924
3  0.628769  0.046953
4  0.675722  0.021791
5  0.697513 -0.003616
6  0.693897 -0.000459
7  0.693438       NaN

In [26]:
x = [1, 4, 6, 5, 3, 1.5, 2.5, 3.5]
n = len(x)
lst = []
for x in range(n):
    a  = None
    lst.append(a)

In [27]:
lst

[None, None, None, None, None, None, None, None]

In [28]:
x = [1, 4, 6, 5, 3, 1.5, 2.5, 3.5]
n = len(x)
[None for i in range(n)]

[None, None, None, None, None, None, None, None]